trigger:
  - none

pool:
  vmImage: windows-latest

resources:
  repositories:
    - repository: RepoEmiAutomatizacionSOCloud
      type: git
      ref: master
      name: SOCloud/_git/SOCloud.Automatizacion.Web

stages:
  - stage: escenarios_socloud
    displayName: Escenarios SOCloud
    jobs:
      - job: ejecutar_escenarios
        displayName: Ejecucion Escenarios
        steps:
          - checkout: RepoEmiAutomatizacion
          - task: JavaToolInstaller@0
            displayName: 'install java'
            inputs:
              versionSpec: 17
              jdkArchitectureOption: x64
              jdkSourceOption: PreInstalled
          - task: CmdLine@2
            displayName: Limpiar Reporte
            inputs:
              script: |
                gradle clearReports
          - task: CmdLine@2
            displayName: Ejecucion Escenarios
            inputs:
              script: |
                gradle clean test aggregate -Denvironment=qa
          - task: CmdLine@2
            displayName: ReEjecucion Escenarios Fallidos
            condition: failed()
            retryCountOnTaskFailure: 2
            inputs:
  #             script: |
  #                gradle test --tests "com.grupoemi.runners.RerunFailedScenarios"
          - task: CopyFiles@2
            displayName: copyTargetFolder
            condition: always()
            inputs:
              SourceFolder: '$(System.DefaultWorkingDirectory)/target/site/serenity'
              Contents: '**'
              TargetFolder: '$(build.artifactstagingdirectory)'
          - task: PublishBuildArtifacts@1
            displayName: publishSerenityReport
            condition: always()
            inputs:
              PathtoPublish: '$(System.DefaultWorkingDirectory)/target/site/serenity'
              ArtifactName: 'Informe Ejecución Escenarios SOCloud'
              publishLocation: 'Container'